temp/unpackaged/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Job_Candidate__c</fullName>
        <label>Job Candidate</label>
        <referenceTo>Job_Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <label>Job Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Years_in_IT__c</fullName>
        <label>Years in IT</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Candidate__c/fields/USA_visa_valid_to__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_to__c</fullName>
    <label>USA visa valid to</label>
    <type>Date</type>
</CustomField>

temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <fields>
        <fullName>HR_Manager__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>HR Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Positions</relationshipLabel>
        <relationshipName>Job_Positions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
                <value>
                    <fullName>Ukraine</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Open_Due_Date__c</fullName>
        <label>Open Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Position_Budget__c</fullName>
        <label>Position Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Practice_Unit__c</fullName>
        <label>Practice Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    public static List<Job_Position__c> generateJobPositions(integer numberOfPositions, Contact hr, Date positionDate, String practiceUnit, String Location) {
        List<Job_Position__c> positions = new List<Job_Position__c>();
        
        for(integer i = 0; i < numberOfPositions; i++){
            positions.add(new Job_Position__c(Name='pos'+i, Practice_Unit__c=practiceUnit, HR_Manager__c=hr.Id, Position_Budget__c=100,
            Open_Due_Date__c=positionDate, Location__c=Location));
        }

        return positions;
    }

    public static List<Job_Candidate__c> generateJobCandidates(integer numberOfCandidates, Boolean isVisaHolder, Date visaFrom,Date visaTo){
        List<Job_Candidate__c> candidates = new List<Job_Candidate__c>();

        for(integer i = 0;i<numberOfCandidates;i++){
            candidates.add (new Job_Candidate__c(Name='cand'+i, Email__c='test@mail.com', Phone_Number__c='123456789', Years_in_IT__c=10, 
            USA_visa_holder__c=isVisaHolder, USA_visa_valid_From__c=visaFrom, USA_visa_valid_to__c=visaTo));
        }
        return candidates;
    }

    public static List<Job_Application__c> generateJobApplications(integer numberOfApplications, Job_Position__c position, Job_Candidate__c candidate){
        List<Job_Application__c> applications = new List<Job_Application__c>();

        for(integer i=0;i<numberOfApplications;i++){
            applications.add(new Job_Application__c(Job_Candidate__c=candidate.Id, Job_Position__c=position.Id));
        }

        return applications;
    }
}