temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <fields>
        <fullName>Open_Due_Date__c</fullName>
        <label>Open Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Position_Budget__c</fullName>
        <label>Position Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Practice_Unit__c</fullName>
        <label>Practice Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobPositionControllerHelper.cls
public class JobPositionControllerHelper {

    public static List<Job_Position__c> getPositionsByPracticeUnit(String practiceUnit){
        List<Job_Position__c> positions;
        if(String.isBlank(practiceUnit)){
            positions = [
                SELECT Id, Name, Position_Budget__c, Open_Due_Date__c, Practice_Unit__c
                FROM Job_Position__c
                WHERE Open_Due_Date__c>=:Date.today()
                WITH SECURITY_ENFORCED
                ORDER BY Priority__c
            ];
        }
        else{
            positions = [
                SELECT Id, Name, Position_Budget__c, Open_Due_Date__c, Practice_Unit__c
                FROM Job_Position__c
                WHERE Open_Due_Date__c >= :Date.today() AND Practice_Unit__c = :practiceUnit
                WITH SECURITY_ENFORCED
                ORDER BY Priority__c
            ];
        }
        return positions;
    }
}