temp/unpackaged/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Job_Candidate__c</fullName>
        <label>Job Candidate</label>
        <referenceTo>Job_Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <label>Job Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requested_Salary__c</fullName>
        <label>Salary I would like to have</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Candidate__c.object
<CustomObject>
    <label>Job Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationControllerHelper.cls
public class JobApplicationControllerHelper {
    public static List<Job_Application__c> getApplicationsByPosition(String positionId) {
        if(positionId==null){
            throw new AuraHandledException('Position didn`t selected');
        }
        List<Job_Application__c> applications= [
            SELECT Id, Requested_Salary__c, Job_Candidate__r.Name, Job_Position__c
            FROM Job_Application__c
            WHERE Job_Position__c=:positionId
            WITH SECURITY_ENFORCED
            ORDER BY Requested_Salary__c
        ];
        return applications;
    }
}