temp/unpackaged/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Job_Candidate__c</fullName>
        <label>Job Candidate</label>
        <referenceTo>Job_Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <label>Job Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Candidate__c.object
<CustomObject>
    <label>Job Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationControllerTest.cls
@isTest
public class JobApplicationControllerTest {
    @TestSetup
    static void makeData() {
        Contact hr = new Contact(LastName='hr contact', MailingCountry='USA');
        insert hr;
        Date positionDate = Date.today();
        Job_Position__c[] position = DataFactory.generateJobPositions(1, hr, positionDate, Constants.PRACTICE_UNIT_SALESFORCE, Constants.JOB_POSITION_LOCATION_Ukraine);
        Job_Candidate__c[] candidate = DataFactory.generateJobCandidates(1, true, positionDate, positionDate.addYears(1));
        insert position;
        insert candidate;
        List<Job_Application__c> applications = DataFactory.generateJobApplications(200, position[0], candidate[0]);
        insert applications;
    }

    @IsTest
    static void getApplicationByPositionIdTest(){
        Job_Position__c position = [SELECT Id FROM Job_Position__c LIMIT 1];
        List<Job_Application__c> applications;
        Test.startTest();
        applications = JobApplicationController.getApplications(position.Id);
        Test.stopTest();

        for(Integer i = 0; i < applications.size(); i++){
            System.assertEquals(position.Id, applications[i].Job_Position__c);
        }
    }
}