temp/unpackaged/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Job_Candidate__c</fullName>
        <label>Job Candidate</label>
        <referenceTo>Job_Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <label>Job Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Candidate__c.object
<CustomObject>
    <label>Job Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
                <value>
                    <fullName>Ukraine</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationTriggerTest.cls
@isTest
public class JobApplicationTriggerTest {
    @TestSetup
    static void makeData(){
        Contact hr = new Contact(LastName='hr contact', MailingCountry='USA');
        insert hr;
        Date positionDate = Date.today();
        Job_Position__c[] application = DataFactory.generateJobPositions(1, hr, positionDate, Constants.PRACTICE_UNIT_SALESFORCE, Constants.JOB_POSITION_LOCATION_USA);
        Job_Candidate__c[] candidate = DataFactory.generateJobCandidates(1, true, positionDate, positionDate.addYears(1));
        insert application;
        insert candidate;
    }

    @IsTest
    static void validateUSACandidateWorkForYearTest(){
        Job_Position__c position = [SELECT Id FROM Job_Position__c WHERE Location__c=:Constants.JOB_POSITION_LOCATION_USA LIMIT 1];
        Job_Candidate__c candidate = [SELECT Id FROM Job_Candidate__c WHERE USA_visa_holder__c=true LIMIT 1];
        List<Job_Application__c> applications = DataFactory.generateJobApplications(200, position, candidate);
        Test.startTest();
        Database.SaveResult[] results = Database.insert(applications, false);
        Test.stopTest();

        for(Database.SaveResult result : results){
            System.assert(!result.isSuccess());
            System.assert(result.getErrors().size()>0);
            System.assertEquals(Constants.CANDIDATE_VISA_LESS_THAN_YEAR_ERROR_MESSAGE, result.getErrors()[0].getMessage());
        }
        
    }
}