temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <fields>
        <fullName>Practice_Unit__c</fullName>
        <label>Practice Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobPositionControllerTest.cls
@isTest
public class JobPositionControllerTest {
    @TestSetup
    static void makeData(){
        Contact hr = new Contact(LastName='hr contact', MailingCountry='USA');
        insert hr;
        Date positionDate = Date.today();
        Job_Position__c[] position = DataFactory.generateJobPositions(200, hr, positionDate, Constants.PRACTICE_UNIT_SALESFORCE, Constants.JOB_POSITION_LOCATION_USA);
        insert position;
    }

    @IsTest
    static void getPositionsByPracticeUnitTest(){
        List<Job_Position__c> positions = new List<Job_Position__c>();
        Test.startTest();
        positions = JobPositionController.getPositions(Constants.PRACTICE_UNIT_SALESFORCE);
        Test.stopTest();

        for(Integer i = 0; i < positions.size(); i++){
            System.assertEquals(Constants.PRACTICE_UNIT_SALESFORCE, positions[i].Practice_Unit__c);
        }
    }

    @IsTest
    static void getPositionsWithBlankPracticeUnitTest(){
        List<Job_Position__c> positions = new List<Job_Position__c>();
        Test.startTest();
        positions = JobPositionController.getPositions('');
        Test.stopTest();

        for(Integer i = 0; i < positions.size(); i++){
            System.assertEquals(Constants.PRACTICE_UNIT_SALESFORCE, positions[i].Practice_Unit__c);
        }
    }
}