temp/unpackaged/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Job_Candidate__c</fullName>
        <label>Job Candidate</label>
        <referenceTo>Job_Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <label>Job Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/unpackaged/objects/Job_Candidate__c.object
<CustomObject>
    <label>Job Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Candidate__c/fields/USA_visa_valid_to__c.field-meta.xml
<CustomField>
    <fullName>USA_visa_valid_to__c</fullName>
    <label>USA visa valid to</label>
    <type>Date</type>
</CustomField>

temp/unpackaged/objects/Job_Position__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
                <value>
                    <fullName>Ukraine</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationHelper.cls
public class JobApplicationHelper {

    public static void validateUSACandidateWorkForYear(List<Job_Application__c> createdJobApplications) {
        List<Id> candidatesIds = new List<Id>();
        List<Id> positionsIds = new List<Id>();
        for(Job_Application__c application: createdJobApplications){
            candidatesIds.add(application.Job_Candidate__c);
            positionsIds.add(application.Job_Position__c);
        }
        
        Map<Id, Job_Candidate__c> candidates = new Map<Id,Job_Candidate__c>([SELECT Id, USA_visa_holder__c, USA_visa_valid_to__c, USA_visa_valid_From__c FROM Job_Candidate__c WHERE Id IN :candidatesIds]);
        Map<Id, Job_Position__c> positions = new Map<Id,Job_Position__c>([SELECT Id,Location__c FROM Job_Position__c WHERE Id IN :positionsIds]);

        for(Job_Application__c application: createdJobApplications){
            Job_Candidate__c candidate = candidates.get(application.Job_Candidate__c);
            if(positions.get(application.Job_Position__c).Location__c==Constants.JOB_POSITION_LOCATION_USA && candidate.USA_visa_holder__c &&
            (System.Today().daysBetween(candidate.USA_visa_valid_to__c)<=365 || candidate.USA_visa_valid_From__c > System.Today())){
                application.addError(Constants.CANDIDATE_VISA_LESS_THAN_YEAR_ERROR_MESSAGE);
            }
        }
    }
}